<?php
/**
 * ProcessRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ProcessMaker\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ProcessMaker API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ProcessMaker\Client;

use PHPUnit\Framework\TestCase;

/**
 * ProcessRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ProcessRequest
 * @package     ProcessMaker\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProcessRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProcessRequest"
     */
    public function testProcessRequest()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "callable_id"
     */
    public function testPropertyCallableId()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "process_id"
     */
    public function testPropertyProcessId()
    {
    }

    /**
     * Test attribute "process_collaboration_id"
     */
    public function testPropertyProcessCollaborationId()
    {
    }

    /**
     * Test attribute "participant_id"
     */
    public function testPropertyParticipantId()
    {
    }

    /**
     * Test attribute "process_category_id"
     */
    public function testPropertyProcessCategoryId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
