<?php
/**
 * GroupMembersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ProcessMaker\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ProcessMaker API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ProcessMaker\Client;

use \ProcessMaker\Client\Configuration;
use \ProcessMaker\Client\ApiException;
use \ProcessMaker\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GroupMembersApiTest Class Doc Comment
 *
 * @category Class
 * @package  ProcessMaker\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GroupMembersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createGroupMember
     *
     * Save a new group member.
     *
     */
    public function testCreateGroupMember()
    {
    }

    /**
     * Test case for deleteGroupMember
     *
     * Delete a group member.
     *
     */
    public function testDeleteGroupMember()
    {
    }

    /**
     * Test case for getGroupMemberById
     *
     * Get single group member by ID.
     *
     */
    public function testGetGroupMemberById()
    {
    }

    /**
     * Test case for getGroupMembers
     *
     * Returns all groups for a given member.
     *
     */
    public function testGetGroupMembers()
    {
    }

    /**
     * Test case for getGroupMembersAvailable
     *
     * Returns all groups available for a given member.
     *
     */
    public function testGetGroupMembersAvailable()
    {
    }

    /**
     * Test case for getUserMembersAvailable
     *
     * Returns all users available for a given member.
     *
     */
    public function testGetUserMembersAvailable()
    {
    }
}
